name: front
toolstack: "php:drupal"

hooks:
    # We run deploy hook after your application has been deployed and started.
    deploy: "cd public ; drush site-install campsite2015 --account-pass=admin"

crons:
    drupal:
        spec: "*/20 * * * *"
        cmd: "cd public ; drush core-cron"
